In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv('./data/emotions_clean.csv')

In [36]:
# define X and y

X = df['clean_tokens_neg']
y = df['emotion']



In [37]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=df["emotion"]
)

In [38]:

#TF - IDF gives a word a higher value when : 1) it appears often in a text and itncommon across all the text"
#implements text encoding 
tf_idf = TfidfVectorizer()

X_train_idf = tf_idf.fit_transform(X_train)
X_Test_idf = tf_idf.transform(X_test)




In [39]:
#testing if the encoder above works

print("Training data:", X_train_idf.shape)
print("Test data:", X_Test_idf.shape)
print()

Training data: (12800, 11182)
Test data: (3200, 11182)



In [40]:
print(X_train.iloc[0])


['feeling', 'drain', 'sit', 'chair']


In [41]:
print(X_train_idf[0])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (1, 11182)>
  Coords	Values
  (0, 3386)	0.2892086532907283
  (0, 2733)	0.5380422979337207
  (0, 9048)	0.44916333197966263
  (0, 1425)	0.6520131453436288


In [ ]:
# Create the model
log_reg = LogisticRegression(max_iter=1000)

# Train
log_reg.fit(X_train_idf, y_train)

# Predict
y_pred = log_reg.predict(X_Test_idf)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.845625

Classification Report:
              precision    recall  f1-score   support

       anger       0.91      0.78      0.84       432
        fear       0.87      0.76      0.81       387
         joy       0.80      0.94      0.87      1072
        love       0.82      0.57      0.67       261
     sadness       0.87      0.92      0.89       933
    surprise       0.86      0.50      0.63       115

    accuracy                           0.85      3200
   macro avg       0.86      0.75      0.79      3200
weighted avg       0.85      0.85      0.84      3200


Confusion Matrix:
[[ 337    7   43    5   40    0]
 [  11  296   43    4   28    5]
 [   7    2 1012   18   30    3]
 [   3    0   97  149   12    0]
 [  11   12   50    4  855    1]
 [   0   24   19    1   14   57]]
